Formats shell scripts and .zshrc

diff --git a/bin/do-times b/bin/do-times
--- a/bin/do-times
+++ b/bin/do-times
@@ -3,7 +3,7 @@
 set -euo pipefail
 
 usage() {
-  cat << EOF >&2
+	cat <<EOF >&2
 Usage: Usage: do-times <times> <command>
 
 Example:
@@ -12,30 +12,33 @@ EOF
 }
 
 main() {
-  if [ "$#" -lt 2 ]; then
-    usage
-    return 1
-  fi
+	if [ "$#" -lt 2 ]; then
+		usage
+		return 1
+	fi
 
-  local times="$1"
-  shift
+	local times="$1"
+	shift
 
-  if ! [[ "$times" =~ ^[0-9]+$ ]]; then
-    usage
-    return 1
-  fi
+	if ! [[ "$times" =~ ^[0-9]+$ ]]; then
+		usage
+		return 1
+	fi
 
-  for i in $(seq 1 "$times"); do
-    "$@" || { printf "\033[31mFAILED\033[0m\n"; break; }
-  done
+	for i in $(seq 1 "$times"); do
+		"$@" || {
+			printf "\033[31mFAILED\033[0m\n"
+			break
+		}
+	done
 
-  printf "\033[35mTo run the same command again, use:\n  for i in \$(seq 1 %d); do " "$times"
+	printf "\033[35mTo run the same command again, use:\n  for i in \$(seq 1 %d); do " "$times"
 
-  for arg in "$@"; do
-    printf "%q " "$arg"
-  done
+	for arg in "$@"; do
+		printf "%q " "$arg"
+	done
 
-  printf "|| { echo \"FAILED\"; break; }; done\033[0m\n" >&2
+	printf "|| { echo \"FAILED\"; break; }; done\033[0m\n" >&2
 }
 
 main "$@"
diff --git a/bin/tmux-single-session b/bin/tmux-single-session
--- a/bin/tmux-single-session
+++ b/bin/tmux-single-session
@@ -3,26 +3,26 @@
 set -euo pipefail
 
 main() {
-  if ! command -v tmux 2>&1 >/dev/null; then
-    echo 'tmux command not found' 2>&1
-    exit 1
-  fi
+	if ! command -v tmux 2>&1 >/dev/null; then
+		echo 'tmux command not found' 2>&1
+		exit 1
+	fi
 
-  if [ "$#" -eq 0 ] || [ "$1" = "new" ] || [ "$1" = "new-session" ]; then
-    if [ -n "${TMUX-}" ]; then
-      echo "tmux session has been already attached" 2>&1
-      exit 1
-    fi
+	if [ "$#" -eq 0 ] || [ "$1" = "new" ] || [ "$1" = "new-session" ]; then
+		if [ -n "${TMUX-}" ]; then
+			echo "tmux session has been already attached" 2>&1
+			exit 1
+		fi
 
-    # attach to an existing tmux session, or create one if none exist
-    if tmux has-session >/dev/null 2>&1 && tmux list-sessions | grep -qE '.*]$'; then
-      tmux attach
-    else
-      tmux attach || tmux new-session
-    fi
-  else
-    tmux "$@"
-  fi
+		# attach to an existing tmux session, or create one if none exist
+		if tmux has-session >/dev/null 2>&1 && tmux list-sessions | grep -qE '.*]$'; then
+			tmux attach
+		else
+			tmux attach || tmux new-session
+		fi
+	else
+		tmux "$@"
+	fi
 }
 
 main "$@"
