Update tmuxx

diff --git a/bin/tmuxx b/bin/tmuxx
--- a/bin/tmuxx
+++ b/bin/tmuxx
@@ -8,24 +8,23 @@
 # https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
 
 if ! type tmux >/dev/null 2>&1; then
-    echo 'Error: tmux command not found' 2>&1
-    exit 1
+  echo 'Error: tmux command not found' 2>&1
+  exit 1
 fi
 
 if [ -n "$TMUX" ]; then
-    echo "Error: tmux session has been already attached" 2>&1
-    exit 1
+  echo "Error: tmux session has been already attached" 2>&1
+  exit 1
 fi
 
 if tmux has-session >/dev/null 2>&1 && tmux list-sessions | grep -qE '.*]$'; then
-    # detached session exists
-    tmux attach && echo "tmux attached session "
+  # detached session exists
+  tmux attach && echo "tmux attached session "
 else
-    if [[ ( $OSTYPE == darwin* ) && ( -x $(which reattach-to-user-namespace 2>/dev/null) ) ]]; then
-        # on OS X force tmux's default command to spawn a shell in the user's namespace
-        tmux_config=$(cat $HOME/.tmux.conf <(echo 'set-option -g default-command "reattach-to-user-namespace -l $SHELL"'))
-        tmux -f <(echo "$tmux_config") new-session && echo "tmux created new session supported OS X"
-    else
-        tmux new-session && echo "tmux created new session"
-    fi
+  if [[ $OSTYPE == darwin* && -x $(command -v reattach-to-user-namespace) ]]; then
+    tweaked_config=$(cat <(echo 'set-option -g default-command "reattach-to-user-namespace -l $SHELL"') $HOME/.tmux.conf)
+    tmux attach || tmux -f <(echo "$tweaked_config") new-session  && echo "tmux created new session supported OS X"
+  else
+    tmux attach || tmux new-session && echo "tmux created new session"
+  fi
 fi
